<?php /** @var \App\View\AmountOfFeesFrom40To60 $this */ ?>

<?php $data = $this->getQueryResults(); ?>
<p><?php echo $data[0]; ?></p>
<table class="table">
    <tr>
        <?php if ($data[1][0]) : ?>
            <?php foreach (array_keys($data[1][0]) as $rowTh) : ?>
                <td><?php echo($rowTh)  ?></td>
            <?php endforeach; ?>
        <?php endif; ?>
    </tr>

<?php foreach ($data[1] as $row) : ?>
    <tr>
        <?php foreach ($row as $cell) :  ?>
            <td><?php echo($cell)  ?></td>
        <?php endforeach;  ?>
    </tr>
    <?php endforeach; ?>
</table>